// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package collector

import (
	"github.com/margostino/job-pulse/configuration"
	"github.com/margostino/job-pulse/db"
	"github.com/margostino/job-pulse/geo"
	"github.com/margostino/job-pulse/scrapper"
)

// Injectors from wire.go:

func NewApp() (*App, error) {
	inputParams := NewInputParams()
	configurationConfiguration := configuration.GetConfig()
	connection := db.Connect(configurationConfiguration)
	geoConnection := geo.Connect(configurationConfiguration)
	scrapperScrapper := scrapper.New()
	app := &App{
		inputParams: inputParams,
		db:          connection,
		geo:         geoConnection,
		scrapper:    scrapperScrapper,
		config:      configurationConfiguration,
	}
	return app, nil
}
